[build]
  command = "npm ci && npm run build"
  publish = "build"
  node_version = "14"  

[[redirects]]              # Optional: Redirects for SPAs
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]        # Optional: Environment variables
  NODE_ENV = "production"
